sonar.projectKey=calcom-upa-testing
sonar.host.url=http://localhost:9000
sonar.token=sqa_58c3011aa8daf2957d121e13eee4aa5ea8d0a43c

# Solo módulos representativos de cal.com + tu proyecto de pruebas
sonar.sources=packages/lib,packages/features,tests
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/__mocks__/**,**/*.generated.*,**/.turbo/**

# Tests
sonar.tests=tests
sonar.test.inclusions=**/test_*.py

# Cobertura Python (requisito de la Parte B)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=6144
sonar.typescript.tsconfigPaths=tsconfig.sonar.json